name: Housekeeping

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  shared:
    uses: dfds/shared-workflows/.github/workflows/automation-housekeeping.yml@master
    secrets: inherit # pragma: allowlist secret
    with:
      delete_head_branch: true
      squash_merge: true
      branch_protection: true
      status_checks: false
